# Generated by Django 2.2.6 on 2019-10-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixinfo', '0002_auto_20191010_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zodiac',
            name='name',
            field=models.CharField(choices=[('鸡', '鸡'), ('牛', '牛'), ('羊', '羊'), ('兔', '兔'), ('马', '马'), ('猴', '猴'), ('蛇', '蛇'), ('龙', '龙'), ('猪', '猪'), ('狗', '狗'), ('虎', '虎'), ('鼠', '鼠')], max_length=12, verbose_name='生肖'),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='qqsh',
            field=models.CharField(choices=[('QING', '琴肖'), ('SHU', '书肖'), ('QI', '棋肖'), ('HUA', '画肖')], max_length=10, verbose_name='琴棋书画肖'),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='season',
            field=models.CharField(choices=[('SPRING', '春肖/东肖/风肖'), ('SUMMER', '秋肖/南肖/云肖'), ('AUTUMN', '夏肖/西肖/雷肖'), ('WINTER', '冬肖/北肖/雨肖')], max_length=12, verbose_name='春夏秋冬肖'),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='z_five_element',
            field=models.CharField(choices=[('Z_FIRE', '火肖'), ('Z_WATER', '水肖'), ('Z_EARTH', '土肖'), ('Z_WOOD', '木肖'), ('Z_METAL', '金肖')], max_length=10, verbose_name='五行肖'),
        ),
    ]
