# Generated by Django 2.2.6 on 2019-10-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixinfo', '0006_auto_20191014_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='haoma',
            name='is_pick',
            field=models.BooleanField(default=True, verbose_name='是否被選'),
        ),
        migrations.AddField(
            model_name='zodiac',
            name='is_pick',
            field=models.BooleanField(default=True, verbose_name='是否被選'),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='name',
            field=models.CharField(choices=[('虎', '虎'), ('鼠', '鼠'), ('龙', '龙'), ('兔', '兔'), ('猴', '猴'), ('猪', '猪'), ('马', '马'), ('鸡', '鸡'), ('牛', '牛'), ('狗', '狗'), ('蛇', '蛇'), ('羊', '羊')], max_length=12, verbose_name='生肖'),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='season',
            field=models.CharField(choices=[('WINTER', '冬肖/北肖/雨肖'), ('AUTUMN', '夏肖/西肖/雷肖'), ('SUMMER', '秋肖/南肖/云肖'), ('SPRING', '春肖/东肖/风肖')], max_length=12, verbose_name='春夏秋冬肖'),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='z_five_element',
            field=models.CharField(choices=[('Z_METAL', '金肖'), ('Z_EARTH', '土肖'), ('Z_WOOD', '木肖'), ('Z_WATER', '水肖'), ('Z_FIRE', '火肖')], max_length=10, verbose_name='五行肖'),
        ),
    ]
