# Generated by Django 2.2.6 on 2019-10-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixinfo', '0007_auto_20191014_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haoma',
            name='is_pick',
            field=models.BooleanField(default=False, verbose_name='是否被選'),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='is_pick',
            field=models.BooleanField(default=False, verbose_name='是否被選'),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='name',
            field=models.CharField(choices=[('羊', '羊'), ('虎', '虎'), ('蛇', '蛇'), ('鼠', '鼠'), ('猴', '猴'), ('鸡', '鸡'), ('猪', '猪'), ('牛', '牛'), ('狗', '狗'), ('兔', '兔'), ('马', '马'), ('龙', '龙')], max_length=12, verbose_name='生肖'),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='season',
            field=models.CharField(choices=[('WINTER', '冬肖/北肖/雨肖'), ('SPRING', '春肖/东肖/风肖'), ('SUMMER', '秋肖/南肖/云肖'), ('AUTUMN', '夏肖/西肖/雷肖')], max_length=12, verbose_name='春夏秋冬肖'),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='z_five_element',
            field=models.CharField(choices=[('Z_FIRE', '火肖'), ('Z_METAL', '金肖'), ('Z_WATER', '水肖'), ('Z_EARTH', '土肖'), ('Z_WOOD', '木肖')], max_length=10, verbose_name='五行肖'),
        ),
    ]
