# Generated by Django 2.2.6 on 2019-10-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixinfo', '0008_auto_20191014_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='haoma',
            old_name='is_pick',
            new_name='is_picked',
        ),
        migrations.RenameField(
            model_name='zodiac',
            old_name='is_pick',
            new_name='is_picked',
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='name',
            field=models.CharField(choices=[('虎', '虎'), ('鼠', '鼠'), ('龙', '龙'), ('牛', '牛'), ('蛇', '蛇'), ('马', '马'), ('猴', '猴'), ('鸡', '鸡'), ('兔', '兔'), ('狗', '狗'), ('猪', '猪'), ('羊', '羊')], max_length=12, verbose_name='生肖'),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='qqsh',
            field=models.CharField(choices=[('HUA', '画肖'), ('QING', '琴肖'), ('QI', '棋肖'), ('SHU', '书肖')], max_length=10, verbose_name='琴棋书画肖'),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='season',
            field=models.CharField(choices=[('SPRING', '春肖/东肖/风肖'), ('WINTER', '冬肖/北肖/雨肖'), ('SUMMER', '秋肖/南肖/云肖'), ('AUTUMN', '夏肖/西肖/雷肖')], max_length=12, verbose_name='春夏秋冬肖'),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='z_five_element',
            field=models.CharField(choices=[('Z_WOOD', '木肖'), ('Z_WATER', '水肖'), ('Z_METAL', '金肖'), ('Z_FIRE', '火肖'), ('Z_EARTH', '土肖')], max_length=10, verbose_name='五行肖'),
        ),
    ]
