# Generated by Django 2.2.6 on 2019-10-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixinfo', '0009_auto_20191014_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='haoma',
            name='be_pick',
            field=models.BooleanField(default=False, verbose_name='是否被選'),
        ),
        migrations.AddField(
            model_name='zodiac',
            name='be_pick',
            field=models.BooleanField(default=False, verbose_name='是否被選'),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='name',
            field=models.CharField(choices=[('虎', '虎'), ('羊', '羊'), ('龙', '龙'), ('马', '马'), ('兔', '兔'), ('鸡', '鸡'), ('蛇', '蛇'), ('狗', '狗'), ('猪', '猪'), ('猴', '猴'), ('鼠', '鼠'), ('牛', '牛')], max_length=12, verbose_name='生肖'),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='qqsh',
            field=models.CharField(choices=[('SHU', '书肖'), ('HUA', '画肖'), ('QING', '琴肖'), ('QI', '棋肖')], max_length=10, verbose_name='琴棋书画肖'),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='season',
            field=models.CharField(choices=[('SUMMER', '秋肖/南肖/云肖'), ('SPRING', '春肖/东肖/风肖'), ('WINTER', '冬肖/北肖/雨肖'), ('AUTUMN', '夏肖/西肖/雷肖')], max_length=12, verbose_name='春夏秋冬肖'),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='z_five_element',
            field=models.CharField(choices=[('Z_FIRE', '火肖'), ('Z_EARTH', '土肖'), ('Z_METAL', '金肖'), ('Z_WOOD', '木肖'), ('Z_WATER', '水肖')], max_length=10, verbose_name='五行肖'),
        ),
    ]
