# Generated by Django 2.2.6 on 2019-10-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixinfo', '0010_auto_20191014_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='haoma',
            name='is_picked',
        ),
        migrations.RemoveField(
            model_name='zodiac',
            name='is_picked',
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='name',
            field=models.CharField(choices=[('羊', '羊'), ('猴', '猴'), ('狗', '狗'), ('牛', '牛'), ('虎', '虎'), ('蛇', '蛇'), ('马', '马'), ('猪', '猪'), ('鸡', '鸡'), ('鼠', '鼠'), ('兔', '兔'), ('龙', '龙')], max_length=12, verbose_name='生肖'),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='season',
            field=models.CharField(choices=[('SUMMER', '秋肖/南肖/云肖'), ('SPRING', '春肖/东肖/风肖'), ('AUTUMN', '夏肖/西肖/雷肖'), ('WINTER', '冬肖/北肖/雨肖')], max_length=12, verbose_name='春夏秋冬肖'),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='z_five_element',
            field=models.CharField(choices=[('Z_METAL', '金肖'), ('Z_WATER', '水肖'), ('Z_FIRE', '火肖'), ('Z_WOOD', '木肖'), ('Z_EARTH', '土肖')], max_length=10, verbose_name='五行肖'),
        ),
    ]
