# Generated by Django 2.2.6 on 2019-10-14 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sixinfo', '0005_auto_20191014_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sysdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_conf', models.BooleanField(default=False, verbose_name='是否**')),
                ('sys_zodiac', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='sixinfo.Zodiac', verbose_name='系统当前年肖')),
            ],
            options={
                'verbose_name': '系统生肖',
                'verbose_name_plural': '系统生肖',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_num', models.CharField(max_length=10, verbose_name='期号')),
                ('issue_opentime', models.DateTimeField(verbose_name='每期开奖时间')),
                ('is_opened', models.BooleanField(default=False, verbose_name='是否开过')),
                ('issue_haoma', models.ForeignKey(on_delete=None, to='sixinfo.Haoma', verbose_name='開獎特碼')),
            ],
            options={
                'verbose_name': '全年期号以及开奖时间表',
                'verbose_name_plural': '全年期号以及开奖时间表',
            },
        ),
    ]
