# Generated by Django 2.2.6 on 2019-10-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysdata',
            name='sys_zodiac',
            field=models.ForeignKey(on_delete=None, to='sixinfo.Zodiac', verbose_name='系统当前年肖'),
        ),
    ]
